[package]
name = "experiments"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
name = "experiments_rs"
path = "lib/src/main/rust/lib.rs"
crate-type = ["staticlib", "cdylib"]

[dependencies]
